apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mongodb
  ports:
  - port: 27017
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongodb
spec:
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:3.2
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  selector:
    app: elasticsearch
  type: NodePort
  ports:
  - port: 9200
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:5.6.12
        env:
        - name: cluster.name
          value: "graylog"
        - name: http.host
          value: "0.0.0.0"
        - name: transport.host
          value: "localhost"
        - name: network.host
          value: "0.0.0.0"
        - name: xpack.security.enabled
          value: "false"
        ports:
        - containerPort: 9200
        - containerPort: 9300

---
apiVersion: v1
kind: Service
metadata:
  name: graylog
spec:
  selector:
    app: graylog
  type: NodePort
  ports:
  - port: 9000
    #nodePort: 30000

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: graylog
  labels:
    app: graylog
spec:
  template:
    metadata:
      labels:
        app: graylog
    spec:
      containers:
      - name: graylog
        image: graylog/graylog:3.0
        env:
        - name: GRAYLOG_MONGODB_URI
          value: mongodb://mongodb/graylog
        - name : GRAYLOG_PASSWORD_SECRET
          value: "somepasswordpepper"
        - name: GRAYLOG_ROOT_PASSWORD_SHA2
          value: "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918"
        - name: GRAYLOG_WEB_ENDPOINT_URI
          value: "http://192.168.99.100:32605/api"
        - name: ELASTICSEARCH_DISCOVERY_ZEN_PING_MULTICAST_ENABLED
          value: "false"
        - name: ELASTICSEARCH_DISCOVERY_ZEN_PING_UNICAST_HOSTS
          value: "elasticsearch:9300"
        ports:
        - containerPort: 9000