# argo cd

- hosts: localhost
  tasks:

  - name: Kubectl create namespace
    command: kubectl create namespace argocd

  - name: Install argo cd
    command: kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/v0.9.2/manifests/install.yaml

  - name: Kubectl wait for rollout
    command: kubectl rollout status deployment/argocd-server -n argocd

  - name: Download argo cli
    get_url:
      url: https://github.com/argoproj/argo-cd/releases/download/v0.9.2/argocd-linux-amd64
      dest: /usr/local/bin/argocd
      mode: 0777